? examples/hello_world.scl
? SCALF "Hello World" program

? Main function (Automatically called if exists)
func:Main() {
    ? System call to write to stdout (1 = file descriptor for stdout)
    |>syscall(1, "Hello, SCALF!\n");

    ? Explicit exit with status code 0
    |>syscall(60, 0);  // 60 = syscall number for exit (Linux x86_64)
}

//
Windows version example

dllcall : "kernel32.dll" > WriteConsoleA(-11, "Hello SCALF!\n", 13, 0, 0)
//